### PR TITLE
fixing broken link to mozilla developer website

### PR DESCRIPTION
**Pull request by lidiazuin**
@fbiville could you please review this one? :) thanks!

### CODE REVIEW

**Review by robsdedude — APPROVED** [review]
:closed_lock_with_key:

**Comment by lidiazuin** [comment]
Please merge this PR if it's all correct. I don't have the permission to do that :)

**Comment by lidiazuin** [comment]
You're right, but this wasn't published yet https://neo4j.com/docs/bolt/current/bolt/message/ - the link is still broken here. I will find it on TeamCity and close this PR as I finish doing that

**Comment by lidiazuin** [comment]
Now it's updated on the website. Thanks for flagging this @robsdedude !

**Pull request closed without merging**
